#define Type SET 1
#define Type DEF 2
#define Type PRINCIPAL 3
#define Type LOOP 4
#define Type INILOOP 5
#define Type FINLOOP 6
#define Type BLAK 7
#define Type NEG 8
#define Type CORCH 9
#define Type SCORCH 10       
#define Type INICOMP 11
#define Type FINCOMP 12
#define Type INIMUSICA 13
#define Type FINMUSICA 14
#define Type ENCASO 15
#define Type CONTRARIO 16
#define Type FINCASO 17
#define Type EJECUTE 18
#define Type SILENC 19
#define Type VALORINICIAL 20
#define Type SALTO 21
#define Type VALOR_MAXIMO 22
#define Type CANTIDAD_REITEROS 23
#define Type CONTADOR 24
#define Type VARIABLE 25           
#define Type OPERADOR 26
#define Type VALOR 27
#define Type ENTONCES 28
#define Type NOTE 29
#define Type IDENTIFIER 30
#define Type NUMBER 31
